pipeline {
    agent {
        kubernetes {
            label 'maven'
            cloud 'openshift'
            defaultContainer 'jnlp'
            serviceAccount 'jenkins'
            yaml """
              kind: Pod
              metadata:
                name: jenkins-slave
              spec:
                containers:
                - name: jnlp
                  image: registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7
                  privileged: false
                  alwaysPullImage: false
                  workingDir: /tmp
                  ttyEnabled: false
                  volumeMounts:
                  - mountPath: '/home/jenkins/.m2'
                    name: pvc
                volumes:
                - name: pvc
                  persistentVolumeClaim:
                    claimName: 'maven-slave-pvc'
            """
        }
    }

    options {
        buildDiscarder(logRotator(daysToKeepStr: '', numToKeepStr: '5'))
    }

    environment {
        APP_NAME = 'student-exam-api'
    }

    parameters {
        choice(
            choices: ['ONE', 'TWO'],
            name: 'PARAMETER_01'
        )
    }

    stages {
        stage('Init') {
            steps {
                script {
                    println 'Initialization Complete!'
                }
            }
            post {
                success {
                    echo 'Init Success'
                }
                failure {
                    echo 'Init Failed'
                }
                always {
                    echo 'Init END'
                }
            }
        }
    }
    post {
        success {
            println 'Stages Success'
        }
        failure {
            println 'Stages failure'
        }
        always {
            println 'Stages always'
        }
    }
}
