import jenkins.*
import jenkins.model.*
import hudson.*
import hudson.model.*
import com.cloudbees.hudson.plugins.folder.*
import org.jenkinsci.plugins.workflow.job.WorkflowJob
import groovy.json.JsonSlurper
import groovy.io.FileType

Jenkins jenkins = Jenkins.instance

def addFolder(folderName ->
    def folder = jenkins.getItem(folderName)
    if (folder == null) {
        folder = jenkins.createProject(Folder.class, folderName)
        println 'Folder Created!'
    } else {
        if (folder.getClass() != Folder.class) {
            folder = jenkins.createProject(Folder.class, folderName)
      	    println 'Folder Created!'
        } else {
            println 'Folder already exists!'
        }
    }
)

pipeline {
    agent {
        kubernetes {
            label 'maven'
            cloud 'openshift'
            defaultContainer 'jnlp'
            serviceAccount 'jenkins'
            yaml """
              kind: Pod
              metadata:
                name: jenkins-slave
              spec:
                containers:
                - name: jnlp
                  image: registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7
                  privileged: false
                  alwaysPullImage: false
                  workingDir: /tmp
                  ttyEnabled: false
                  volumeMounts:
                  - mountPath: '/home/jenkins/.m2'
                    name: pvc
                volumes:
                - name: pvc
                  persistentVolumeClaim:
                    claimName: 'maven-slave-pvc'
            """
        }
    }

    options {
        buildDiscarder(logRotator(daysToKeepStr: '', numToKeepStr: '3'))
    }

    environment {
        //APP_NAME = 'student-exam-api'
    }

    parameters {
        choice(
            choices: ['TEMP', 'DEV', 'TEST', 'UAT', 'PROD'],
            name: 'ENVIRONMENT'
        )
    }

    stages {
        stage ('Init') {
            steps {
                script {
                    println "Environment Selected => ${env.ENVIRONMENT}"
                }
            }
            post {
                success {
                    echo 'Init Success'
                }
                failure {
                    echo 'Init Failed'
                }
            }
        }
        stage ('Add-Folder') {
            steps {
                script {
                    addFolder(env.ENVIRONMENT)
                }
            }
            post {
                success {
                    echo 'Folder added Successfully'
                }
                failure {
                    echo 'Failed adding folder'
                }
            }
        }
    }
    post {
        success {
            println 'Stages Success'
        }
        failure {
            println 'Stages failure'
        }
        always {
            println 'Stages always'
        }
    }
}
