---
apiVersion: v1
kind: Template
labels:
  template: 'grad-config-maps'
metadata:
  name: 'grad-config-maps'
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-algorithm-api-config-map
    data:
      GRAD_TRAX_API: 'https://educ-grad-trax-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_STUDENT_API: 'https://educ-grad-student-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_COURSE_API: 'https://educ-grad-course-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      APP_LOG_LEVEL: DEBUG
      GRAD_ASSESSMENT_API: 'https://educ-grad-assessment-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_PROGRAM_API: 'https://educ-grad-program-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      MAX_RETRY_ATTEMPTS: '3'
      GRAD_RULE_PROCESSOR_API: 'https://educ-rule-engine-api-77c02f-dev.apps.silver.devops.gov.bc.ca'
      GRAD_STUDENT_GRADUATION_API: 'https://educ-grad-student-graduation-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-api-config-map
    data:
      CONNECTION_TIMEOUT: '60000'
      SPRING_SHOW_REQUEST_DETAILS: 'true'
      MAX_LIFETIME: '600000'
      MAXIMUM_POOL_SIZE: '15'
      TZ: America/Vancouver
      MAX_URI_TAGS: '200'
      APP_LOG_LEVEL: DEBUG
      SPRING_WEB_LOG_LEVEL: INFO
      SPRING_BOOT_AUTOCONFIG_LOG_LEVEL: INFO
      SPRING_SECURITY_LOG_LEVEL: INFO
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-assessment-api-config-map
    data:
      APP_LOG_LEVEL: DEBUG
      ENABLE_FLYWAY: 'true'
      GRAD_PROGRAM_API: 'https://educ-grad-program-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_TRAX_API: 'https://educ-grad-trax-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-batch-api-config-map
    data:
      APP_LOG_LEVEL: DEBUG
      ENABLE_FLYWAY: 'false'
      GRADUATE_STUDENT: 'https://educ-grad-graduation-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/graduate/studentid/%s/run/GS'
      GRADUATE_STUDENT_REPORT_ONLY: 'https://educ-grad-graduation-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/graduate/studentid/%s/run/FMR'
      GRADUATION_STUDENT_RECORD: 'https://educ-grad-student-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/student/studentid/%s'
      INFO_FROM_PEN: 'https://student-api-75e61b-tools.apps.silver.devops.gov.bc.ca/api/v1/student?pen=%s'
      KEYCLOAK_TOKEN_URL: 'https://soam-tools.apps.silver.devops.gov.bc.ca/auth/realms/master/protocol/openid-connect/token'
      LIST_STUDENTS_FOR_GRADUATION: 'https://educ-grad-student-api-77c02f-dev.apps.silver.devops.gov.bc.ca/api/v1/student/recalculate'
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-batch-graduation-api-config-map
    data:
      APP_LOG_LEVEL: DEBUG
      ENABLE_FLYWAY: 'true'
      GRAD_GRADUATION_API: 'https://educ-grad-graduation-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_STUDENT_API: 'https://educ-grad-student-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      KEYCLOAK_TOKEN_URL: 'https://soam-tools.apps.silver.devops.gov.bc.ca/'
      PEN_API: 'https://student-api-75e61b-tools.apps.silver.devops.gov.bc.ca/'
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-business-api-config-map
    data:
      APP_LOG_LEVEL: DEBUG
      GRAD_GRADUATION_API: 'https://educ-grad-graduation-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_STUDENT_API: 'https://educ-grad-student-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      KEYCLOAK_TOKEN_URL: 'https://soam-tools.apps.silver.devops.gov.bc.ca/'
      MAX_RETRY_ATTEMPTS: '3'
      PEN_API: 'https://student-api-75e61b-tools.apps.silver.devops.gov.bc.ca/'
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-course-api-config-map
    data:
      APP_LOG_LEVEL: INFO
      ENABLE_FLYWAY: 'true'
      GRAD_PROGRAM_API: 'https://educ-grad-program-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      MAX_RETRY_ATTEMPTS: '3'
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-data-conversion-api-config-map
    data:
      GRAD_STUDENT_API: 'https://educ-grad-student-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      BASELINE_ON_MIGRATE: 'false'
      ENABLE_STUDENT_ID_PEN_XREF: 'true'
      APP_LOG_LEVEL: INFO
      GRAD_PROGRAM_API: 'https://educ-grad-program-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      PEN_STUDENT_API: 'https://student-api-75e61b-tools.apps.silver.devops.gov.bc.ca/'
      PAGE_SIZE: '2000'
      ENABLE_FLYWAY: 'true'
      KEYCLOAK_TOKEN_URL: 'https://soam-tools.apps.silver.devops.gov.bc.ca/'
      ENABLE_GRAD_UPDATE: 'true'
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-distribution-api-config-map
    data:
      APP_LOG_LEVEL: DEBUG
      GRAD_GRADUATION_REPORT_API: 'https://educ-grad-graduation-report-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_REPORT_API: 'https://educ-grad-report-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_STUDENT_API: 'https://educ-grad-student-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_TRAX_API: 'https://educ-grad-trax-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      KEYCLOAK_TOKEN_URL: 'https://soam-tools.apps.silver.devops.gov.bc.ca/'
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-graduation-api-config-map
    data:
      APP_LOG_LEVEL: DEBUG
      EDUC_SCHOOL_API: 'https://school-api-75e61b-tools.apps.silver.devops.gov.bc.ca/'
      GRAD_ALGORITHM_API: 'https://educ-grad-algorithm-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_GRADUATION_REPORT_API: 'https://educ-grad-graduation-report-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_PROGRAM_API: 'https://educ-grad-program-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_REPORT_API: 'https://educ-grad-report-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_STUDENT_API: 'https://educ-grad-student-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_STUDENT_GRADUATION_API: 'https://educ-grad-student-graduation-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      PEN_API: 'https://student-api-75e61b-tools.apps.silver.devops.gov.bc.ca/'
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-graduation-report-api-config-map
    data:
      APP_LOG_LEVEL: DEBUG
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-nats-messaging-config-map
    data:
      CRON_SCHEDULED_PROCESS_EVENTS_STAN: 0 0/5 * * * *
      CRON_SCHEDULED_PROCESS_EVENTS_STAN_LOCK_AT_LEAST_FOR: 800ms
      CRON_SCHEDULED_PROCESS_EVENTS_STAN_LOCK_AT_MOST_FOR: 900ms
      NATS: 'nats://nats.75e61b-tools.svc.cluster.local:4222'
      NATS_MAX_RECONNECT: '60'
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-program-api-config-map
    data:
      APP_LOG_LEVEL: INFO
      ENABLE_FLYWAY: 'true'
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-report-api-config-map
    data:
      APP_LOG_LEVEL: DEBUG
      ENABLE_FLYWAY: 'true'
      GRAD_REPORT_API: 'https://educ-grad-report-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_TRAX_API: 'https://educ-grad-trax-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-rule-engine-api-config-map
    data:
      APP_LOG_LEVEL: DEBUG
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-student-api-config-map
    data:
      APP_LOG_LEVEL: DEBUG
      ENABLE_FLYWAY: 'true'
      GRAD_GRADUATION_REPORT_API: 'https://educ-grad-graduation-report-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_PROGRAM_API: 'https://educ-grad-program-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_STUDENT_GRADUATION_API: 'https://educ-grad-student-graduation-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      GRAD_TRAX_API: 'https://educ-grad-trax-api-77c02f-dev.apps.silver.devops.gov.bc.ca/'
      MAX_RETRY_ATTEMPTS: '3'
      PEN_API: 'https://student-api-75e61b-tools.apps.silver.devops.gov.bc.ca/'
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-student-graduation-api-config-map
    data:
      APP_LOG_LEVEL: DEBUG
      ENABLE_FLYWAY: 'true'
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-trax-api-config-map
    data:
      APP_LOG_LEVEL: INFO
      BASELINE_ON_MIGRATE: 'false'
      CRON_SCHEDULED_PROCESS_JOBS_STAN: 0 0/30 * * * *
      ENABLE_FLYWAY: 'true'
      ENABLE_TRAX_UPDATE: 'false'
      MAX_RETRY_ATTEMPTS: '3'
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: grad-admin-frontend-config-map
    data:
      VUE_APP_TRAX_API_HOST: 'https://educ-grad-trax-api-77c02f-dev.apps.silver.devops.gov.bc.ca'
      VUE_APP_BATCH_GRADUATION_API_HOST: 'https://educ-grad-batch-graduation-api-77c02f-dev.apps.silver.devops.gov.bc.ca'
      VUE_APP_STUDENT_GRADUATION_API_HOST: 'https://educ-grad-student-graduation-api-77c02f-dev.apps.silver.devops.gov.bc.ca'
      VUE_APP_GRADUATION_API_HOST: 'https://educ-grad-graduation-api-77c02f-dev.apps.silver.devops.gov.bc.ca'
      VUE_APP_KEYCLOAK_AUTH_HOST: 'https://soam-tools.apps.silver.devops.gov.bc.ca'
      VUE_APP_ASSESSMENT_API_HOST: 'https://educ-grad-assessment-api-77c02f-dev.apps.silver.devops.gov.bc.ca'
      VUE_APP_BASE_URL: 'https://dev.grad.gov.bc.ca/'
      VUE_APP_COURSE_API_HOST: 'https://educ-grad-course-api-77c02f-dev.apps.silver.devops.gov.bc.ca'
      VUE_APP_STUDENTS_API_HOST: 'https://educ-grad-student-api-77c02f-dev.apps.silver.devops.gov.bc.ca'
      VUE_APP_GRADUATION_REPORT_API_HOST: 'https://educ-grad-graduation-report-api-77c02f-dev.apps.silver.devops.gov.bc.ca'
      VUE_APP_GRAD_REPORT_API_HOST: 'https://educ-grad-report-api-77c02f-dev.apps.silver.devops.gov.bc.ca'
      VUE_APP_PROGRAM_API_HOST: 'https://educ-grad-program-api-77c02f-dev.apps.silver.devops.gov.bc.ca'

  #==========================================================================#
 # Fluent Bit Config Maps (Move these to Secrets as they contain the token) #
#==========================================================================#
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-course-api-flb-sc-config-map
    data:
      fluent-bit.conf: |
        [SERVICE]
           Flush        1
           Daemon       Off
           Log_Level    debug
           HTTP_Server   On
           HTTP_Listen   0.0.0.0
           HTTP_Port     2020
           Parsers_File parsers.conf
        [INPUT]
           Name   tail
           Path   /mnt/log/*
           Exclude_Path *.gz,*.zip
           Parser docker
           Mem_Buf_Limit 20MB
        [FILTER]
           Name record_modifier
           Match *
           Record hostname ${HOSTNAME}
        [OUTPUT]
           Name   stdout
           Match  *
        [OUTPUT]
           Name  splunk
           Match *
           Host  gww.splunk.educ.gov.bc.ca
           Port  443
           TLS         On
           TLS.Verify  Off
           Message_Key educ-grad-course-api
           Splunk_Token replace-this-with-token
      parsers.conf: |

        [PARSER]
            Name        docker
            Format      json
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-data-conversion-api-flb-sc-config-map
    data:
      fluent-bit.conf: |
        [SERVICE]
           Flush        1
           Daemon       Off
           Log_Level    debug
           HTTP_Server   On
           HTTP_Listen   0.0.0.0
           HTTP_Port     2020
           Parsers_File parsers.conf
        [INPUT]
           Name   tail
           Path   /mnt/log/*
           Exclude_Path *.gz,*.zip
           Parser docker
           Mem_Buf_Limit 20MB
        [FILTER]
           Name record_modifier
           Match *
           Record hostname ${HOSTNAME}
        [OUTPUT]
           Name   stdout
           Match  *
        [OUTPUT]
           Name  splunk
           Match *
           Host  gww.splunk.educ.gov.bc.ca
           Port  443
           TLS         On
           TLS.Verify  Off
           Message_Key educ-grad-data-conversion-api
           Splunk_Token replace-this-with-token
      parsers.conf: |

        [PARSER]
            Name        docker
            Format      json
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-program-api-flb-sc-config-map
    data:
      fluent-bit.conf: |
        [SERVICE]
           Flush        1
           Daemon       Off
           Log_Level    debug
           HTTP_Server   On
           HTTP_Listen   0.0.0.0
           HTTP_Port     2020
           Parsers_File parsers.conf
        [INPUT]
           Name   tail
           Path   /mnt/log/*
           Exclude_Path *.gz,*.zip
           Parser docker
           Mem_Buf_Limit 20MB
        [FILTER]
           Name record_modifier
           Match *
           Record hostname ${HOSTNAME}
        [OUTPUT]
           Name   stdout
           Match  *
        [OUTPUT]
           Name  splunk
           Match *
           Host  gww.splunk.educ.gov.bc.ca
           Port  443
           TLS         On
           TLS.Verify  Off
           Message_Key educ-grad-program-api
           Splunk_Token replace-this-with-token
      parsers.conf: |

        [PARSER]
            Name        docker
            Format      json
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-student-api-flb-sc-config-map
    data:
      fluent-bit.conf: |
        [SERVICE]
           Flush        1
           Daemon       Off
           Log_Level    debug
           HTTP_Server   On
           HTTP_Listen   0.0.0.0
           HTTP_Port     2020
           Parsers_File parsers.conf
        [INPUT]
           Name   tail
           Path   /mnt/log/*
           Exclude_Path *.gz,*.zip
           Parser docker
           Mem_Buf_Limit 20MB
        [FILTER]
           Name record_modifier
           Match *
           Record hostname ${HOSTNAME}
        [OUTPUT]
           Name   stdout
           Match  *
        [OUTPUT]
           Name  splunk
           Match *
           Host  gww.splunk.educ.gov.bc.ca
           Port  443
           TLS         On
           TLS.Verify  Off
           Message_Key educ-grad-student-api
           Splunk_Token replace-this-with-token
      parsers.conf: |

        [PARSER]
            Name        docker
            Format      json
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: educ-grad-trax-api-flb-sc-config-map
    data:
      fluent-bit.conf: |
        [SERVICE]
           Flush        1
           Daemon       Off
           Log_Level    debug
           HTTP_Server   On
           HTTP_Listen   0.0.0.0
           HTTP_Port     2020
           Parsers_File parsers.conf
        [INPUT]
           Name   tail
           Path   /mnt/log/*
           Exclude_Path *.gz,*.zip
           Parser docker
           Mem_Buf_Limit 20MB
        [FILTER]
           Name record_modifier
           Match *
           Record hostname ${HOSTNAME}
        [OUTPUT]
           Name   stdout
           Match  *
        [OUTPUT]
           Name  splunk
           Match *
           Host  gww.splunk.educ.gov.bc.ca
           Port  443
           TLS         On
           TLS.Verify  Off
           Message_Key educ-grad-trax-api
           Splunk_Token replace-this-with-token
      parsers.conf: |

        [PARSER]
            Name        docker
            Format      json


