version: "3"
services:
    redis-1:
        image: redis
        command: ["redis-server","/etc/redis/redis.conf"]
        volumes:
            - ./redis/node-1/data:/data
            - ./redis/node-1/conf/redis.conf:/etc/redis/redis.conf
        network_mode: "host"
    redis-2:
        image: redis
        command: ["redis-server", "/etc/redis/redis.conf"]
        volumes:
            - ./redis/node-2/data:/data
            - ./redis/node-2/conf/redis.conf:/etc/redis/redis.conf
        network_mode: "host"
    redis-3:
        image: redis
        command: ["redis-server", "/etc/redis/redis.conf"]
        volumes:
            - ./redis/node-3/data:/data
            - ./redis/node-3/conf/redis.conf:/etc/redis/redis.conf
        network_mode: "host"
    redis-4:
        image: redis
        command: ["redis-server", "/etc/redis/redis.conf"]
        volumes:
            - ./redis/node-4/data:/data
            - ./redis/node-4/conf/redis.conf:/etc/redis/redis.conf
        network_mode: "host"
    redis-5:
        image: redis
        command: ["redis-server", "/etc/redis/redis.conf"]
        volumes:
            - ./redis/node-5/data:/data
            - ./redis/node-5/conf/redis.conf:/etc/redis/redis.conf
        network_mode: "host"
    redis-6:
        image: redis
        command: ["redis-server", "/etc/redis/redis.conf"]
        volumes:
            - ./redis/node-6/data:/data
            - ./redis/node-6/conf/redis.conf:/etc/redis/redis.conf
        network_mode: "host"