name: Update Keycloak
env:
  BRANCH: "Keycloack_scripts"
  REPO_NAME: educ-grad-tools
  KC_BASE_URL: ${{ secrets.KC_BASE_URL}}
  KC_PASSWORD: ${{ secrets.KC_PASSWORD}}
  KC_USERNAME: ${{ secrets.KC_USERNAME}}
  KC_REALM_ID: master
  SCRIPTS_PATH: https://raw.githubusercontent.com/bcgov/${{ env.REPO_NAME }}/${{ env.BRANCH }}/Keycloak
 
on:
  workflow_dispatch:
  push:
    branches:
      - Keycloack_scripts
      
jobs:
  update-keycolak:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Update Keycloak
        run: >
         curl -s ${{ env.SCRIPTS_PATH }}/update-kc.sh | bash /dev/stdin  ${{ env.KC_BASE_URL }} ${{ env.KC_PASSWORD }} ${{ env.KC_USERNAME }} ${{ env.KC_REALM_ID }} ${{ env.SCRIPTS_PATH }} 
        
            
